#!/bin/sh

# Configure background
exec wal -R &

# Start compositor
killall compton
exec compton --config ~/.config/compton/config &

# Start polybar
killall polybar
exec polybar -c ~/.config/polybar/config bar &

# Start notification daemon
exec dunst &

exec blueberry-tray &

# Ping to keep internet up, silly connection
exec $(sleep 1 && ~/.bin/pinger.sh) &


# Start some chat apps
eval $(sleep 1 && slack -u) &
eval $(sleep 1 && discord) &
eval $(sleep 1 && steam -silent) &
