set directory=$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME

set nocompatible
filetype off
syntax on
filetype plugin indent on
set number
set ruler
set visualbell
set encoding=utf-8
set scrolloff=3
set ttyfast
set showmode
set showcmd
set t_Co=256
set background=dark


