#! /bin/sh

sxhkd &

~/.config/bspwm/session &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12

bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Peek state=floating
